<a href="https://colab.research.google.com/github/peeyushsinghal/dimensionality_reduction/blob/main/Dimensionality_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dimensionality Reduction

## Singular Value Decomposition (SVD)

### SVD using Numpy

In [1]:
import numpy as np

In [2]:
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
A

array([[3, 4, 3],
       [1, 2, 3],
       [4, 2, 1]])

In [5]:
#Performing SVD
U, S, VT = np.linalg.svd(A)
print (f'U = \n{U} \n S = \n {S} \n VT = {VT} ')

U = 
[[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]] 
 S = 
 [7.87764972 2.54031671 0.69958986] 
 VT = [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]] 


In [6]:
#Checking if we can remake the original matrix using U,S,VT
A_remake = (U @ np.diag(S) @ VT)
print(A_remake)

[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


### SVD using scikit-learn (TruncatedSVD)

In [7]:
#Importing required modules
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [19]:
#Creating array 
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
A

array([[3, 4, 3],
       [1, 2, 3],
       [4, 2, 1]])

In [21]:
#Fitting the SVD class
n_components = 2
trun_svd =  TruncatedSVD(n_components = n_components)
A_transformed = trun_svd.fit_transform(A)

In [18]:
print("Singular values:")
print(trun_svd.singular_values_)

Singular values:
[7.87764972 2.54031671]


In [22]:
#Printing the transformed matrix
print(f'Transformed Matrix: with {n_components} components')
print(A_transformed)

Transformed Matrix: with 2 components
[[ 5.7942733  -0.46723885]
 [ 3.3604414  -1.58000033]
 [ 4.14622666  1.93351902]]


## Principal Component Analysis (PCA)